### PR TITLE
hopefully make the steps a littler clearer/more obvious

### LINKED ISSUE #109: Improve the setup guide
- reword to make the initial dependency installation steps more obvious 
- add links to useful resources to help install things like mongodb, phantomjs etc
- consider mentioning pa11y webservice as a dependency at this stage?

### PR DESCRIPTION
**Pull request by hollsk**
Resolves #109. Really it's just expanding the instructions to two lines so it's harder for the eye to skip over them.

### CODE REVIEW

**Comment by rowanmanning** [comment]
It's best/simpler _not_ to install the webservice separately in most cases, and let it get installed as part of the `npm install`. Otherwise this looks like an improvement.

The fact that you didn't know it's better to install both together means our docs aren't good enough on that front though! We should fix that I guess :/

**Comment by hollsk** [comment]
Yes! I was struggling to remember. When Jose, Nick, and I got started it up, i think we _had_ to set up the webservice separately as it didn't install itself :/

Should I just remove the webservice sentence entirely?

**Comment by rowanmanning** [comment]
Yeah I reckon removing that sentence would be enough. I'm intrigued as to why you couldn't get it working as a single thing, that's deffo not ideal! I'll try a fresh install myself and see if it works as expected

**Comment by hollsk** [comment]
Cheers - have removed that sentence!

**Comment by rowanmanning** [comment]
Looks great 👍

**Pull request merged**
