### PR TITLE
Better client-side validation

### LINKED ISSUE #83: Url validator
Validate URLs so that people can't do stupid things like only putting one slash after http (ahem)

### PR DESCRIPTION
**Pull request by frvge**
I made the timeout and wait also required because the server gave errors when either one of them was not set.

Integration tests are passing. JS CS is giving some output, but as I didn't change anything there, I'll ignore that.

Fixes #83

### CODE REVIEW

**Comment by rowanmanning** [comment]
Hi @frvge. I noticed this the other day too, but actually these shouldn't be required – it's an error in the backend. I'm looking at fixing the root cause :) thanks for opening, but I'll close once a fix is in.

**Review by rowanmanning — CHANGES_REQUESTED** [review]
Oh actually I just looked properly. I'm happy to merge the name/URL validations but could you remove the validations for timeout/wait?

**Comment by frvge** [comment]
@rowanmanning changes done.

**Comment by rowanmanning** [comment]
Thanks for this, @frvge!

**Review by rowanmanning — APPROVED** [review]

**Pull request merged**
