### PR TITLE
Improve the console messaging on starting the app to avoid confusion.

### PR DESCRIPTION
**Pull request by sangitamane**

### CODE REVIEW

**Comment by danyalaytekin** [comment]
Hey @sangitamane, this looks helpful - it would have helped me to understand the IPV6 issue I experienced with `pa11y-webservice` earlier.

I've made a couple of revisions to present the intended URL alongside the actual URL reported.  Please review and let me know whether you're happy with the changes.

It also resolves the confusing placement (in `main`) of some of the webservice's logging into the dashboard's logging.

**Comment by danyalaytekin** [comment]
|`main`'s logging|PR's original logging|Revised logging|
|---|---|---|
| image | image | image |

**Review by sangitamane — COMMENTED** [review]
Oops looks like I can't approve this!

**Comment by danyalaytekin** [comment]
😄 Thanks for the soft approval though.  @jpw @hollsk @josebolos what do you think?

**Review by danyalaytekin — APPROVED** [review]

**Comment by danyalaytekin** [comment]
Tried approving but, as is logical, it didn't work.  Well played, repo settings, well played 👀

**Review by hollsk — APPROVED** [review]
OH YEAH this has been annoying me for AGES but not enough for me to do anything about it, vg update 🙈 😆 

thanks both! 🙏

**Pull request merged**
