### PR TITLE
Updated results page

### PR DESCRIPTION
**Pull request by emusatova**
# The list of updates for the results page

1. Change layout from an accordion to tabs (see screenshot 1).

2. Each error/warning/notice/ignore rule is a single panel, sorted by the number of selectors (from max to min) (see screenshot 1).

3. The number in panel header has a tooltip to explain that it is about the number of selectors (see screenshot 2).

4. Show/hide details link collapses problem details, like the list of techniques/solutions and list of problematic selectors (see screenshot 3).

5. Add a solutions list: the set of techniques to fix a problem. 
Help new people in accessibility topic understand a problem and teach them how to fix it correctly  (see screenshot 4).

6. Add a selectors list. Show the full list of problematic elements (see screenshot 5).

7. The context for each element is in the popover. Easy to select the piece of HTML to find the element in the code base (see screenshot 6).

8. Update 'Back to top' button (see screenshot 7).

9. Update graph buttons styles (see screenshot 8).

10. Reformat less code.

**Screen 1**
screen_1

**Screen 2**
screen_2

**Screen 3**
screen_3

**Screen 4**
screen_4

**Screen 5**
screen_5

**Screen 6**
screen_6

**Screen 7**
screen_7

**Screen 8**
screen_8

### CODE REVIEW

**Comment by rowanmanning** [comment]
@emusatova this looks amazing! I'm going to try and get it reviewed today, but thank you so much for all the hard work :)

**Comment by emusatova** [comment]
@rowanmanning Nice, waiting for comments :)

**Comment by rowanmanning** [comment]
Code is looking good, it's been a while since I worked on the front end of dashboard but looks like you found where everything lives. I'm going to pull this down locally and test the interface now and then get back to you after that 👍

**Comment by hollsk** [comment]
The whole Pa11y team is blown away by this, @emusatova 😍

**Review by rowanmanning — APPROVED** [review]
Everything looking good locally, will merge and cut a release ASAP. Thanks again for your work on this :)

**Pull request merged**
