### PR TITLE
Updated screenshots for readme

### PR DESCRIPTION
**Pull request by JeremyEnglert**
Addresses https://github.com/pa11y/pa11y-dashboard/issues/202.

### CODE REVIEW

**Comment by joeyciechanowicz** [comment]
This looks great, thanks for doing this!

I think that the second screenshot of a results page should include all three parts of the reports; errors, warnings and notices.

**Comment by JeremyEnglert** [comment]
Sorry for the delay. I updated the second screen. I used a different sample site as this showed the lines better than the previous sites.

**Review by joeyciechanowicz — APPROVED** [review]
Fantasitc, good lookin' image! Thanks for contributing.

**Comment by joeyciechanowicz** [comment]
@JeremyEnglert can you rebase your PR against `master` and fix your merge conflicts?

**Comment by JeremyEnglert** [comment]
I'm going to resubmit this as a new PR. I didn't realize I submitted it from my own master branch.

**Pull request closed without merging**
