### PR TITLE
Fix tests, test more, support Node 16-20

### PR DESCRIPTION
**Pull request by danyalaytekin**
### Changes

- Deps
    - use `pa11y-webservice@4.2.0`
    - use Mocha 10
    - replace use of obsolete `request` with `node-fetch` (can move to native fetch in next major version)
    - add `pa11y-lint-config`
    - replace `underscore` with `lodash.groupby` and `lodash.keys`
- Building
    - replace Make with npm scripts for everything except `less` and `uglify`
    - fix local URLs so they're unaffected by IPV6 issues (arrived with Node 16/18 I think)
- Testing, linting
    - integration tests
        - make them run again, rather than just `setup.js`
            - also remove a `describe.only()`
        - fix bugs caused by webservice fixture changes and Cheerio typo
        - assign new DB name to avoid clash for webservice devs (maybe fully randomise this in future PR)
        - detach from config file dependency
        - promisify some parts
    - lint with ESLint and `pa11y-lint-config`
    - allow ES2019 (can't go higher until drop Node 12)
    - GitHub Actions testing workflow
        - test against Node.js 12, 14, 16, 18, 20 (next major version will drop non-LTS)
        - add MongoDB compatibility tests (independently of those now present in `pa11y-webservice`, so that this project can test its own stated support)
        - extract linting into its own job
        - bump actions deps
        - replace `npm install` with `npm ci`
        - wait for `pa11y-webservice` to be available, rather than sleeping for 10s
- Dev help
    - supply `.nvmrc` (went with 14 because of Apple Silicon)
- Update docs
    - report these changes 
    - add new support policy
    - tidy up

### CODE REVIEW

**Comment by danyalaytekin** [comment]
Some build errors after updating `pa11y-webservice` to `4.3.0`... checking.

**Comment by danyalaytekin** [comment]
I've fixed poor spelling of `lodash.groupby` both in this repo and in `pa11y-webservice`:

- https://github.com/pa11y/pa11y-webservice/pull/157

Fixing `pa11y-webservice` back to `~4.2.0` for now even though npm weirdness might have allowed it through.

**Comment by danyalaytekin** [comment]
`pa11y-webservice@4.3.1` is now in npm.  This one hasn't been reviewed yet so I'll try it here, and will close draft 319 if all goes well:

- #319

**Comment by danyalaytekin** [comment]
^ It works!

**Review by klodr — APPROVED** [review]

**Review by hollsk — APPROVED** [review]
Looks great! I notice there are some Github Actions lint warnings for `test/integration/route/task/index.js` because it doesn't like the length of those mocked URLs. I don't know how hard GA is going to go on this though as it doesn't seem to have failed the checks, just warned us about the lines in question. I leave it in your hands to decide what you want to do about it at the moment, as it's not like it's going to affect the operation of anything 😅

**Comment by danyalaytekin** [comment]
Thanks @hollsk for the review.  Re: linter warnings, these ones seem pretty valid.  I don't think the lines under test were changed by this PR, but I'll create a separate PR to separate them into different lines and quieten those nags.

**Pull request merged**
